import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import { Header } from "@/components/layout/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "CookFlow — AI cooking to-do list",
  description:
    "Turn your day into a timed cooking to-do list, grocery list, smart substitutions, and a budget check — generated by AI.",
  applicationName: "CookFlow",
  authors: [{ name: "CookFlow" }],
  keywords: ["cooking", "meal planning", "to-do list", "grocery list", "budget", "AI"],
  openGraph: {
    title: "CookFlow — AI cooking to-do list",
    description:
      "Turn your day into a timed cooking to-do list, grocery list, smart substitutions, and a budget check.",
    type: "website",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafaf9" },
    { media: "(prefers-color-scheme: dark)", color: "#0c0a09" },
  ],
  width: "device-width",
  initialScale: 1,
};

// Sets the theme class before paint to avoid a flash of the wrong theme.
const themeScript = `(function(){try{var k='cookflow:theme:v1',t=localStorage.getItem(k);if(t!=='light'&&t!=='dark'){t=window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}var e=document.documentElement;e.classList.toggle('dark',t==='dark');e.style.colorScheme=t;}catch(e){}})();`;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Nonce minted per-request by middleware; required by the strict CSP.
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script nonce={nonce} dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body>
        <a href="#main" className="skip-link">
          Skip to content
        </a>
        <Header />
        {children}
      </body>
    </html>
  );
}
